import "./globals.css";

import type { Metadata } from "next";

import Footer from "@/components/footer/index";
import Nav from "@/components/header/Header";

import Providers from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <Nav />
        <body className="pt-16">{children}</body>
        <Footer />
      </Providers>
    </html>
  );
}
